### ISSUE TITLE
ML inference

### ISSUE THREAD

**Issue by Archfx** [PrimeshShamilka/fabric_defect_detector#1]
Primesh, Can you provide an inferred model for this Model which can be directly used for the predictions. Thanks

**Comment by PrimeshShamilka** [comment]
@Archfx Thanks for mentioning this. I have included a demonstration as to how to use an inferred model directly for predictions.
Please check out the demo from here.
https://github.com/PrimeshShamilka/fabric_defect_detector#how-to-run
